const menuList = [
    {
        title:'首页',
        key:'/home'
    },
    {
        title:'警务处置',
        key:'/handle'
    },
    {
        title:'警员视图',
        key:'/police'
    },
    {
        title:'建言献策',
        key:'/advice'
    },
    {
        title:'系统设置',
        key:'/setting',
        children:[
            {
                title:'用户管理',
                key:'/setting/user',
            },
            {
                title:'角色管理',
                key:'/setting/role',
            },
            {
                title:'日志管理',
                key:'/setting/daily',
            }
        ]
    }
];
export default menuList;